theme: minima
title: Siddhartha Home
author: sidd60
email: siddpurwar@gmailcom
description: > # this means to ignore newlines until "baseurl:"
  This is the my personal website, I am planning to write blogs, my view and upload uplaod the resume
  And yes of course, I am open to work with you :)
# social links
github_username:  https://github.com/sidd6p # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
